propulsion_basic:
  label: 'Propulsion spatiale'
  category: Propulsion
  description: 'Maîtrise des moteurs ioniques et de la navigation subluminique.'
  base_cost:
    metal: 120
    crystal: 80
    hydrogen: 40
  base_time: 50
  growth_cost: 1.65
  growth_time: 1.6
  max_level: 10
  requires: { }
  requires_lab: 1
  image: assets/svg/illustrations/research/propulsion.svg
life_support:
  label: 'Systèmes de survie'
  category: Ingénierie
  description: 'Contrôle environnemental, recyclage et maintien des équipages.'
  base_cost:
    metal: 90
    crystal: 110
    hydrogen: 40
  base_time: 55
  growth_cost: 1.6
  growth_time: 1.55
  max_level: 10
  requires: { }
  requires_lab: 1
  image: assets/svg/illustrations/research/engineering.svg
miniaturisation:
  label: 'Miniaturisation des systèmes'
  category: Ingénierie
  description: 'Réduction des composants pour optimiser la place à bord.'
  base_cost:
    metal: 140
    crystal: 150
    hydrogen: 60
  base_time: 60
  growth_cost: 1.65
  growth_time: 1.6
  max_level: 10
  requires:
    life_support: 2
  requires_lab: 1
  image: assets/svg/illustrations/research/engineering.svg
armor_basic:
  label: 'Blindage de base'
  category: Défense
  description: 'Plaques composites et renforts structurels élémentaires.'
  base_cost:
    metal: 160
    crystal: 120
    hydrogen: 40
  base_time: 65
  growth_cost: 1.65
  growth_time: 1.65
  max_level: 10
  requires:
    miniaturisation: 2
  requires_lab: 1
  image: assets/svg/illustrations/research/defense.svg
weapon_light:
  label: 'Armes légères'
  category: Armement
  description: 'Lasers, canons automatiques et missiles à courte portée.'
  base_cost:
    metal: 150
    crystal: 170
    hydrogen: 60
  base_time: 70
  growth_cost: 1.65
  growth_time: 1.6
  max_level: 10
  requires:
    miniaturisation: 2
  requires_lab: 1
  image: assets/svg/illustrations/research/armament.svg
radar_basic:
  label: 'Détection basique'
  category: Capteurs
  description: 'Radars tactiques et balayage à courte portée.'
  base_cost:
    metal: 110
    crystal: 160
    hydrogen: 60
  base_time: 65
  growth_cost: 1.6
  growth_time: 1.55
  max_level: 10
  requires:
    miniaturisation: 1
  requires_lab: 1
  image: assets/svg/illustrations/research/sensors.svg
armor_enhanced:
  label: 'Blindage renforcé'
  category: Défense
  description: 'Alliages avancés et champs de confinement structurels.'
  base_cost:
    metal: 260
    crystal: 210
    hydrogen: 90
  base_time: 90
  growth_cost: 1.7
  growth_time: 1.65
  max_level: 10
  requires:
    armor_basic: 5
  requires_lab: 2
  image: assets/svg/illustrations/research/defense.svg
shield_energy:
  label: 'Boucliers énergétiques'
  category: Défense
  description: 'Générateurs de champs déflecteurs et boucliers phaseurs.'
  base_cost:
    metal: 240
    crystal: 260
    hydrogen: 140
  base_time: 95
  growth_cost: 1.72
  growth_time: 1.65
  max_level: 10
  requires:
    armor_enhanced: 3
    weapon_light: 4
  requires_lab: 2
  image: assets/svg/illustrations/research/defense.svg
weapon_medium:
  label: 'Armes moyennes'
  category: Armement
  description: 'Torpilles lourdes et batteries laser à longue portée.'
  base_cost:
    metal: 260
    crystal: 280
    hydrogen: 160
  base_time: 100
  growth_cost: 1.7
  growth_time: 1.65
  max_level: 10
  requires:
    weapon_light: 6
  requires_lab: 2
  image: assets/svg/illustrations/research/armament.svg
logistics:
  label: 'Logistique spatiale'
  category: Ingénierie
  description: 'Ravitaillement interplanétaire et coordination des convois.'
  base_cost:
    metal: 220
    crystal: 200
    hydrogen: 140
  base_time: 90
  growth_cost: 1.68
  growth_time: 1.62
  max_level: 10
  requires:
    propulsion_basic: 4
    life_support: 4
  requires_lab: 2
  image: assets/svg/illustrations/research/engineering.svg
engineering_heavy:
  label: 'Ingénierie lourde'
  category: Ingénierie
  description: 'Conception de structures massives et docks orbitaux.'
  base_cost:
    metal: 320
    crystal: 260
    hydrogen: 160
  base_time: 110
  growth_cost: 1.72
  growth_time: 1.68
  max_level: 10
  requires:
    logistics: 3
  requires_lab: 2
  image: assets/svg/illustrations/research/engineering.svg
reactor_advanced:
  label: 'Réacteurs avancés'
  category: Propulsion
  description: 'Réacteurs à fusion haute densité et confinement magnétique.'
  base_cost:
    metal: 380
    crystal: 340
    hydrogen: 200
  base_time: 130
  growth_cost: 1.75
  growth_time: 1.7
  max_level: 10
  requires:
    propulsion_basic: 5
    engineering_heavy: 2
  requires_lab: 3
  image: assets/svg/illustrations/research/propulsion.svg
weapon_heavy:
  label: 'Armes lourdes'
  category: Armement
  description: 'Railguns, canons à plasma et plates-formes multi-batteries.'
  base_cost:
    metal: 420
    crystal: 380
    hydrogen: 260
  base_time: 140
  growth_cost: 1.75
  growth_time: 1.72
  max_level: 10
  requires:
    weapon_medium: 5
    reactor_advanced: 2
  requires_lab: 3
  image: assets/svg/illustrations/research/armament.svg
tactical_coordination:
  label: 'Coordination tactique'
  category: Commandement
  description: 'IA stratégique et communications quantiques longue portée.'
  base_cost:
    metal: 360
    crystal: 420
    hydrogen: 200
  base_time: 135
  growth_cost: 1.7
  growth_time: 1.68
  max_level: 10
  requires:
    radar_basic: 5
    logistics: 5
  requires_lab: 3
  image: assets/svg/illustrations/research/command.svg
superstructures:
  label: Superstructures
  category: Ingénierie
  description: 'Coques modulaires géantes et architecture segmentée.'
  base_cost:
    metal: 520
    crystal: 460
    hydrogen: 260
  base_time: 150
  growth_cost: 1.78
  growth_time: 1.72
  max_level: 10
  requires:
    engineering_heavy: 5
  requires_lab: 4
  image: assets/svg/illustrations/research/engineering.svg
reactor_antimatter:
  label: 'Réacteurs à antimatière'
  category: Propulsion
  description: 'Confinement annulaire et catalyseurs d’antimatière.'
  base_cost:
    metal: 620
    crystal: 540
    hydrogen: 340
  base_time: 170
  growth_cost: 1.8
  growth_time: 1.75
  max_level: 10
  requires:
    reactor_advanced: 6
    superstructures: 3
  requires_lab: 4
  image: assets/svg/illustrations/research/propulsion.svg
weapon_capital:
  label: 'Armement capital'
  category: Armement
  description: 'Super-canons, bombardement orbital et charges de siège.'
  base_cost:
    metal: 680
    crystal: 620
    hydrogen: 360
  base_time: 180
  growth_cost: 1.82
  growth_time: 1.76
  max_level: 10
  requires:
    weapon_heavy: 6
    superstructures: 4
  requires_lab: 4
  image: assets/svg/illustrations/research/armament.svg
defense_multilayer:
  label: 'Défense multi-couches'
  category: Défense
  description: 'Combinaison de boucliers adaptatifs et d’armures composites.'
  base_cost:
    metal: 640
    crystal: 560
    hydrogen: 340
  base_time: 175
  growth_cost: 1.78
  growth_time: 1.74
  max_level: 10
  requires:
    armor_enhanced: 6
    shield_energy: 5
  requires_lab: 4
  image: assets/svg/illustrations/research/defense.svg
stellar_shipyards:
  label: 'Chantiers stellaires'
  category: Construction
  description: 'Assemblage orbital massif et infrastructures d’amarrage.'
  base_cost:
    metal: 720
    crystal: 660
    hydrogen: 420
  base_time: 185
  growth_cost: 1.8
  growth_time: 1.76
  max_level: 10
  requires:
    superstructures: 5
    engineering_heavy: 7
  requires_lab: 4
  image: assets/svg/illustrations/research/construction.svg
autonomous_hangars:
  label: 'Hangars autonomes'
  category: Construction
  description: 'Réseaux de lancement automatisés pour escadrilles de chasseurs.'
  base_cost:
    metal: 760
    crystal: 680
    hydrogen: 440
  base_time: 190
  growth_cost: 1.8
  growth_time: 1.78
  max_level: 10
  requires:
    stellar_shipyards: 2
    tactical_coordination: 4
  requires_lab: 4
  image: assets/svg/illustrations/research/construction.svg
super_weapon:
  label: 'Armes de destruction massive'
  category: Armement
  description: 'Rayons planétaires, bombardements orbitaux et super-armes.'
  base_cost:
    metal: 880
    crystal: 760
    hydrogen: 520
  base_time: 210
  growth_cost: 1.85
  growth_time: 1.8
  max_level: 10
  requires:
    weapon_capital: 4
    reactor_antimatter: 4
  requires_lab: 5
  image: assets/svg/illustrations/research/armament.svg
fleet_networks:
  label: 'Réseaux stratégiques de flotte'
  category: Commandement
  description: 'Commandement interstellaire et coordination des armadas.'
  base_cost:
    metal: 820
    crystal: 780
    hydrogen: 480
  base_time: 205
  growth_cost: 1.82
  growth_time: 1.78
  max_level: 10
  requires:
    tactical_coordination: 6
    autonomous_hangars: 3
  requires_lab: 5
  image: assets/svg/illustrations/research/command.svg
