<?php

return [
    'metal_mine' => [
        'label' => 'Mine de métal',
        'base_cost' => ['metal' => 60, 'crystal' => 15],
        'base_time' => 20,
        'growth_cost' => 1.6,
        'growth_time' => 1.6,
        'prod_base' => 100,
        'prod_growth' => 1.15,
        'energy_use_base' => 10,
        'energy_use_growth' => 1.10,
        'energy_use_linear' => true,
        'affects' => 'metal',
        'image' => 'assets/svg/illustrations/buildings/metal-mine.svg',
        'requires' => [
            'buildings' => [],
            'research' => [],
        ],
    ],
    'crystal_mine' => [
        'label' => 'Mine de cristal',
        'base_cost' => ['metal' => 48, 'crystal' => 24],
        'base_time' => 25,
        'growth_cost' => 1.6,
        'growth_time' => 1.6,
        'prod_base' => 50,
        'prod_growth' => 1.15,
        'energy_use_base' => 15,
        'energy_use_growth' => 1.10,
        'energy_use_linear' => true,
        'affects' => 'crystal',
        'image' => 'assets/svg/illustrations/buildings/crystal-mine.svg',
        'requires' => [
            'buildings' => [],
            'research' => [],
        ],
    ],
    'solar_plant' => [
        'label' => 'Centrale solaire',
        'base_cost' => ['metal' => 120, 'crystal' => 60],
        'base_time' => 30,
        'growth_cost' => 1.6,
        'growth_time' => 1.6,
        'prod_base' => 100,
        'prod_growth' => 1.12,
        'energy_use_base' => 0,
        'energy_use_growth' => 1.0,
        'energy_use_linear' => false,
        'affects' => 'energy',
        'image' => 'assets/svg/illustrations/buildings/solar-plant.svg',
        'requires' => [
            'buildings' => [],
            'research' => [],
        ],
    ],
    'fusion_reactor' => [
        'label' => 'Réacteur à fusion',
        'base_cost' => ['metal' => 900, 'crystal' => 360, 'hydrogen' => 180],
        'base_time' => 60,
        'growth_cost' => 1.55,
        'growth_time' => 1.6,
        'prod_base' => 320,
        'prod_growth' => 1.18,
        'energy_use_base' => 0,
        'energy_use_growth' => 1.0,
        'energy_use_linear' => false,
        'affects' => 'energy',
        'image' => 'assets/svg/illustrations/buildings/fusion-reactor.svg',
        'requires' => [
            'buildings' => [
                'solar_plant' => 5,
                'hydrogen_plant' => 3,
            ],
            'research' => [
                'reactor_advanced' => 2,
            ],
        ],
        'upkeep' => [
            'hydrogen' => ['base' => 30, 'growth' => 1.16],
        ],
    ],
    'hydrogen_plant' => [
        'label' => 'Générateur d’hydrogène',
        'base_cost' => ['metal' => 150, 'crystal' => 100],
        'base_time' => 35,
        'growth_cost' => 1.6,
        'growth_time' => 1.6,
        'prod_base' => 30,
        'prod_growth' => 1.15,
        'energy_use_base' => 20,
        'energy_use_growth' => 1.10,
        'energy_use_linear' => true,
        'affects' => 'hydrogen',
        'image' => 'assets/svg/illustrations/buildings/hydrogen-plant.svg',
        'requires' => [
            'buildings' => ['solar_plant' => 1],
            'research' => [],
        ],
    ],
    'storage_depot' => [
        'label' => 'Entrepôt planétaire',
        'base_cost' => ['metal' => 1000, 'crystal' => 400],
        'base_time' => 55,
        'growth_cost' => 1.6,
        'growth_time' => 1.6,
        'prod_base' => 0,
        'prod_growth' => 1.0,
        'energy_use_base' => 0,
        'energy_use_growth' => 1.0,
        'energy_use_linear' => false,
        'affects' => 'storage',
        'image' => 'assets/svg/illustrations/buildings/storage-depot.svg',
        'requires' => [
            'buildings' => [
                'metal_mine' => 4,
                'crystal_mine' => 3,
            ],
            'research' => [
                'logistics' => 2,
            ],
        ],
        'storage' => [
            'metal' => ['base' => 50000, 'growth' => 1.6],
            'crystal' => ['base' => 40000, 'growth' => 1.6],
            'hydrogen' => ['base' => 30000, 'growth' => 1.6],
            'energy' => ['base' => 2500, 'growth' => 1.5],
        ],
    ],
    'research_lab' => [
        'label' => 'Laboratoire Helios',
        'base_cost' => ['metal' => 200, 'crystal' => 320, 'hydrogen' => 80],
        'base_time' => 40,
        'growth_cost' => 1.65,
        'growth_time' => 1.6,
        'prod_base' => 0,
        'prod_growth' => 1.0,
        'energy_use_base' => 22,
        'energy_use_growth' => 1.22,
        'energy_use_linear' => true,
        'affects' => 'energy',
        'image' => 'assets/svg/illustrations/buildings/research-lab.svg',
        'requires' => [
            'buildings' => [
                'solar_plant' => 1,
                'crystal_mine' => 1,
            ],
            'research' => [],
        ],
    ],
    'shipyard' => [
        'label' => 'Chantier spatial Asterion',
        'base_cost' => ['metal' => 420, 'crystal' => 260, 'hydrogen' => 120],
        'base_time' => 45,
        'growth_cost' => 1.7,
        'growth_time' => 1.65,
        'prod_base' => 0,
        'prod_growth' => 1.0,
        'energy_use_base' => 35,
        'energy_use_growth' => 1.25,
        'energy_use_linear' => true,
        'affects' => 'energy',
        'image' => 'assets/svg/illustrations/buildings/shipyard.svg',
        'requires' => [
            'buildings' => ['research_lab' => 1],
            'research' => ['engineering_heavy' => 1],
        ],
    ],
];
